### ISSUE TITLE
Chunk Texture Management (global texture arrays?)

### ISSUE THREAD

**Issue by apachano** [GentenStudios/quartz-engine#108]
@beeperdeeper089, please fill out what needs to be done here then add Todo tag

**Comment by beeperdeeper089** [comment]
We need to figure out a way to effeciently manage textures within the Chunk system. We currently load in the textures again and again for EACH chunk, which is inefficient and we should keep like a global texture array.

**Comment by beeperdeeper089** [comment]
This is now obselete.
