### ISSUE TITLE
Handle Allocator for Graphics Resources

### ISSUE THREAD

**Issue by beeperdeeper089** [GentenStudios/quartz-engine#112]
We need a handle allocator for storing a reference to a graphics resource that a certain thing is using.

@DontBelieveMe has already begun work on this, however the freeing of this and the automatic shifting within the Allocator's internal data needs to be implemented.

**Comment by DontBelieveMe** [comment]
I'm going to close this and create another issue for addressing the maximum number of handles that can be allocated and the no freeing.
