### ISSUE TITLE
Create shaders from source text as well as from file.

### ISSUE THREAD

**Issue by DontBelieveMe** [GentenStudios/quartz-engine#116]
Currently shaders can only be loaded from file - `IRenderDevice::createShaderPipeline(pathToFile, layout)`.  
An extra function should be added that allows the creation of shaders from the source text. 
This would offer greater flexibility in how shaders are loaded - at some point shaders could be loaded from a resource manager for example.

Ideas:
  - Change `IRenderDevice::createShaderPipeline(...)` to `IRenderDevice::createShaderFromFile(...)`
  - Add extra virtual method `IRenderDevice::createShaderFromSource(...)` that accepts the source code of the shader instead the filepath of the shdader.
  - Should then do the same job as `createShaderFromFile` - e.g. parse the shader and create the graphics resource in the same manner.

Note:
  - This may require that a filepath is passed in as well as the source code - The shader parser needs a filepath that it will resolve `#include` directives in the shader code relative to.

**Comment by 138paulmiller** [comment]
currently working on this
