### ISSUE TITLE
Simple Multithreading Tools

### ISSUE THREAD

**Issue by beeperdeeper089** [GentenStudios/quartz-engine#118]
Multithreading is an important part of improving performance throughout the engine, and derived games.

We need to have (at some point):
  - Thread Pool (naive impl. in place currently)
  - Single Thread Worker (which executes ``std::function<void()>``s from a queue)
  - CUSTOM Single Thread Worker (which executes an ``std::function<void(const T&)>`` where ``T`` is the type data stored in the queue, for example in a logger, maybe a LogMessage object)
  - CUSTOM Thread Pool (literally the CUSTOM single thread worker, but as a thread pool.)

I currently have implementations for all of these in my own engine, I will be porting these over very soon once they are exception free for the most part.

**Comment by Xaleth** [comment]
Looks like #119 was simple enough for this issue.
