### ISSUE TITLE
Concerns about code of conduct

### ISSUE THREAD

**Issue by Xaleth** [GentenStudios/quartz-engine#81]
The current code of conduct is pretty vague. Just a quick run down of the certain standards:

>Using welcoming and inclusive language

Define welcoming and inclusive language. It is ambiguous if this project becomes big and many people with many different opinions may come to different terms with this. If you want be truly tolerant, then tolerate the intolerant, unless they're trolling, which is a different story.

>Gracefully accepting constructive criticism

Seriously, define this. What if the criticism was something a person didn't like, regardless of credibility, and the maintainers have no choice but to comply with the complaints in order to align with the code of conduct.

>Showing empathy towards other community members

Completely unnecessary for especially a software project.

>Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

Like I said, opinions and definitions vary for each person, and legitimate stuff may be cancelled due to not being aligned with the vague code of conduct.

If you guys actually put definitions of words such as "inclusive" in the conduct, then this whole issue would be useless.

P.S. the definition of inclusive is this 
```
adj.
Taking a great deal or everything within its scope; comprehensive
```

**Comment by earthcrafterman** [comment]
What's wrong with trolling? Trolling should be banned during serious discussion, but are people like Ken M really that bad?

**Comment by earthcrafterman** [comment]
Also, why is trolling included with insulting/derogatory comments, and personal or political attacks?

**Comment by beeperdeeper089** [comment]
Hmm, we *could* do another Code of Conduct but this was the default GitHub provided and at the time I couldn't be bothered to look for anything else. If you know any better Code of Conducts that we can just copy paste, please say as that would make things a lot easier. Thanks for bringing this up :)

**Comment by beeperdeeper089** [comment]
Ah didn't see the bottom :joy: (I'm on mobile and can't read lol), we can add the definitions in at the bottom, or you could do it if you're confident (I'm not the man to be looking at for Code of Conducts)?

**Comment by apachano** [comment]
Certainly can be revamped although there is a fair amount to be said about defaults. In addition, what is the limit to which we clarify and revamp? Personally, I am a fan of common sense and learned norms, if it was up to me alone there would be no code of conduct included.

I agree that opinions and definitions vary by person, just as what may or may not be "legitimate" does. This is unavoidable with any sort of large group of people and no matter what someone will likely be unhappy with another's interpretation and outlining rules won't prevent this.

`Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.`

I think this should also help clarify some things. Essentially, if you are unsure if something is appropriate it should be okay to reach out to project staff, (and moderators when the community grows) as they will remain active and hopefully on the same page with what is appropriate conduct and what is not for this specific community.

This all being said, if anyone is interested in suggesting specific edits please do. They are all welcome (pending discussion of course). As far as providing definitions in the code I lean against it as certain people will have issues with certain words and we can't define every word used in the document (as well as words in the definitions). If there is confusion staff would be a good resource for definition as staff will also be able to provide contextual support.

P.S. Another definition of inclusive:
`Not excluding any section of society or any party involved in something.`
