### ISSUE TITLE
Cursor doesn't hide when camera is enabled, but is always visible.

### ISSUE THREAD

**Issue by beeperdeeper089** [GentenStudios/quartz-engine#92]
What is says on the tin.

The function ``GLWindow::setCursorPosition`` doesn't work properly, although it is the same code as it once was. I've tried going through the documentation and doing what they say but that doesn't work either, so I'm completely stumped as to the root cause of this problem.

**Comment by SuperFola** [comment]
Tried https://stackoverflow.com/questions/4999401/hiding-the-cursor-warp-mouse-sdl-1-3 but didn't work

**Comment by DontBelieveMe** [comment]
Fixed by 5b9d4f95b6d69a1ab4d57f0f8bcd470e211240e9
